// Run against an isolated, freshly seeded synthetic database using run.py.
import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
const { chromium } = await import(process.env.SYMSOIL_PLAYWRIGHT_MODULE || 'playwright')
const base = process.env.SYMSOIL_TEST_URL || 'http://127.0.0.1:8000'
const password = process.env.SYMSOIL_DEMO_PASSWORD
if (!password) throw new Error('Set an explicit synthetic test password')
const artifacts = process.env.SYMSOIL_TEST_ARTIFACTS
if (artifacts) await mkdir(artifacts, { recursive: true })
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] })
const errors = [], external = [], passed = []
const contexts = []
async function actor(username, width = 1440) {
  const context = await browser.newContext({ viewport: { width, height: width < 600 ? 844 : 1000 } })
  contexts.push(context)
  const page = await context.newPage()
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', req => { if (!req.url().startsWith(base)) external.push(req.url()) })
  await page.goto(base)
  await page.getByLabel('用户名', { exact: true }).fill(username)
  await page.getByLabel('密码', { exact: true }).fill(password)
  await page.getByRole('button', { name: '进入工作台', exact: true }).click()
  await page.getByRole('heading', { name: /^你好，/ }).waitFor()
  return page
}
async function ready(page, label) {
  await page.getByRole('heading', { name: label, exact: true }).waitFor()
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `overflow: ${label}`)
}
async function nav(page, name) {
  await page.locator('nav[aria-label="主要功能"]').getByRole('button', { name, exact: true }).click()
  await ready(page, name)
}
async function topic(page) {
  await nav(page, '看议题')
  await page.getByRole('button', { name: '查看观点与方案' }).first().click()
  await page.getByRole('heading', { name: '合成演示：周末公共场地工作坊', exact: true }).waitFor()
}
async function snapshot(page, name) {
  if (artifacts) await page.screenshot({ path: `${artifacts}/${name}.png`, fullPage: true })
}
async function waitNotice(page, text) { await page.getByRole('status').filter({ hasText: text }).waitFor() }
try {
  const qiao = await actor('qiao')
  const lin = await actor('lin')
  await snapshot(qiao, 'desktop-workbench')
  assert.equal(await qiao.getByRole('button', { name: '发起议题', exact: true }).count(), 0)
  await nav(qiao, '查资料')
  await qiao.getByLabel('搜索社区资料').fill('表达')
  await qiao.getByRole('button', { name: '查找资料', exact: true }).click()
  await qiao.locator('article').filter({ hasText: '合成示例：表达与授权' }).getByRole('button', { name: '查看原文与来源' }).click()
  await qiao.getByRole('dialog').getByText('R0产品使用说明合成样本').waitFor()
  await qiao.getByRole('button', { name: '关闭窗口' }).click()
  passed.push('资料关键词查询与原文来源')

  await nav(qiao, '说想法')
  await qiao.getByRole('button', { name: '写一个私稿', exact: true }).click()
  await qiao.getByLabel('想法标题').fill('合成测试：我关心清理条件')
  await qiao.getByLabel('我的原话', { exact: true }).fill('我暂时不接受清理任务；需要先核实工具和时间。')
  await qiao.getByRole('button', { name: '保存私人原话', exact: true }).click()
  await waitNotice(qiao, '私稿已保存')
  await topic(lin)
  assert.equal(await lin.locator('.viewpoint').count(), 0)
  await qiao.getByRole('button', { name: '本人确认这版准确' }).click()
  await waitNotice(qiao, '尚未因此增加分享权限')
  await lin.getByRole('button', { name: '刷新版本', exact: true }).click()
  assert.equal(await lin.locator('.viewpoint').count(), 0)
  passed.push('私人原话与确认不分享')

  await qiao.getByRole('button', { name: '预览并选择分享' }).click()
  await qiao.getByLabel('分享到哪个议题').selectOption({ label: '合成演示：周末公共场地工作坊' })
  await qiao.getByRole('checkbox').check()
  await qiao.getByRole('button', { name: '分享预览中的唯一正文' }).click()
  await waitNotice(qiao, '已按预览')
  await lin.getByRole('button', { name: '刷新版本', exact: true }).click()
  await lin.locator('.viewpoint').filter({ hasText: '我暂时不接受清理任务' }).waitFor()
  await qiao.getByRole('button', { name: '编辑原话', exact: true }).click()
  await qiao.getByLabel('我的原话', { exact: true }).fill('我愿意先核实工具；这不表示接受清理劳动。')
  await qiao.getByRole('button', { name: '保存私人原话', exact: true }).click()
  await waitNotice(qiao, '新版需要本人重新确认')
  await lin.getByRole('button', { name: '刷新版本', exact: true }).click()
  await lin.getByText('暂时没有共享观点。未分享的私人原话不会出现在这里。').waitFor()
  await qiao.getByRole('button', { name: '本人确认这版准确' }).waitFor()
  passed.push('显式分享、跨成员读取、编辑失效')

  await topic(qiao)
  await qiao.getByRole('button', { name: '表达我的立场' }).first().click()
  await qiao.getByRole('radio', { name: '有条件支持', exact: true }).check()
  await qiao.getByLabel('支持的必要条件（必填）').fill('先获得场地同意，并明确清理工具。')
  await qiao.getByRole('button', { name: '保存我对这一版的立场' }).click()
  await qiao.locator('.stance-list').filter({ hasText: '先获得场地同意' }).waitFor()
  passed.push('方案版本与有条件立场')

  await nav(qiao, '做事情')
  await qiao.getByRole('button', { name: '核对条款并回应' }).first().click()
  await qiao.getByRole('radio', { name: '我想协商条件' }).check()
  await qiao.getByLabel('我的补充说明').fill('合成测试：我需要先确认工具。')
  await qiao.getByRole('button', { name: '保存本人回应' }).click()
  await waitNotice(qiao, '回应')
  await qiao.getByRole('button', { name: '核对条款并回应' }).first().click()
  await qiao.getByRole('radio', { name: '我拒绝这次邀请' }).check()
  await qiao.getByRole('button', { name: '保存本人回应' }).click()
  await qiao.getByText('已拒绝', { exact: true }).waitFor()
  passed.push('本人协商与拒绝，保持独立事实')

  await lin.getByRole('button', { name: '邀请承担任务' }).click()
  await lin.getByLabel('邀请谁').selectOption({ label: '乔雨 · 合成成员' })
  for (const [label, value] of [['任务名称','合成测试：核查工具目录'],['具体范围','仅核查目录，不承诺劳动'],['完成标准','记录工具是否齐全'],['提供的资源','合成目录'],['报酬或自愿性质','合成自愿邀请，无实际履约']]) {
    await lin.getByLabel(label, { exact: true }).fill(value)
  }
  await lin.getByRole('button', { name: '发出合成测试邀请' }).click()
  await waitNotice(lin, '邀请')
  await nav(qiao, '做事情')
  await qiao.locator('article').filter({ hasText: '合成测试：核查工具目录' }).getByRole('button', { name: '核对条款并回应' }).click()
  await qiao.getByRole('radio', { name: '我接受这些条款' }).check()
  await qiao.getByRole('button', { name: '保存本人回应' }).click()
  await qiao.locator('article').filter({ hasText: '合成测试：核查工具目录' }).getByText('已接受', { exact: true }).waitFor()
  passed.push('发起人邀请与受邀本人接受')

  const admin = await actor('admin')
  await nav(admin, '说想法')
  await admin.getByText('这里还没有你的私稿', { exact: true }).waitFor()
  await admin.locator('nav[aria-label="主要功能"]').getByRole('button', { name: '账号管理', exact: true }).click()
  await ready(admin, '账号管理')
  await admin.getByRole('button', { name: '建立加入邀请' }).click()
  await admin.getByLabel('用户名', { exact: true }).fill('newcomer')
  await admin.getByLabel('显示称呼').fill('合成新成员')
  await admin.getByRole('button', { name: '生成一次性加入邀请' }).click()
  const token = await admin.getByLabel('一次性邀请口令', { exact: true }).inputValue()
  assert.ok(token.length > 20)
  await admin.getByRole('button', { name: '已交付，清除页面口令' }).click()
  const newcomerContext = await browser.newContext()
  contexts.push(newcomerContext)
  const newcomer = await newcomerContext.newPage()
  await newcomer.goto(base)
  await newcomer.getByRole('button', { name: '我有加入邀请' }).click()
  await newcomer.getByLabel('一次性邀请口令').fill(token)
  await newcomer.getByLabel('设置密码').fill(password)
  await newcomer.getByRole('button', { name: '建立本地账号', exact: true }).click()
  await newcomer.getByLabel('用户名', { exact: true }).fill('newcomer')
  await newcomer.getByLabel('密码', { exact: true }).fill(password)
  await newcomer.getByRole('button', { name: '进入工作台', exact: true }).click()
  await ready(newcomer, '你好，合成新成员。')
  await admin.locator('nav[aria-label="主要功能"]').getByRole('button', { name: '账号管理', exact: true }).click()
  await admin.locator('article').filter({ hasText: '合成新成员' }).getByRole('button', { name: '冻结账号' }).click()
  await admin.getByRole('button', { name: '确认冻结账号' }).click()
  await waitNotice(admin, '冻结')
  await newcomer.getByRole('button', { name: /^查资料/ }).last().click()
  await newcomer.getByRole('heading', { name: '回到社区工作台' }).waitFor()
  passed.push('管理员隔离、一次性注册、冻结撤销会话')

  const mobile = await actor('qiao', 390)
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
  await snapshot(mobile, 'mobile-workbench')
  await mobile.getByRole('button', { name: '写下我的想法', exact: true }).click()
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
  await snapshot(mobile, 'mobile-expression-dialog')
  await mobile.getByRole('button', { name: '关闭窗口' }).click()
  await mobile.getByRole('button', { name: '退出账号' }).click()
  await mobile.getByRole('heading', { name: '回到社区工作台' }).waitFor()
  await mobile.reload()
  await mobile.getByRole('heading', { name: '回到社区工作台' }).waitFor()
  assert.equal(await mobile.evaluate(() => localStorage.length), 0)
  passed.push('手机布局、弹窗、退出及刷新不恢复账号')
  assert.deepEqual(errors, [], 'browser exceptions')
  assert.deepEqual(external, [], 'external resources')
  console.log(JSON.stringify({ passed, browser: browser.version(), errors, external }, null, 2))
} finally {
  for (const context of contexts) await context.close()
  await browser.close()
}
